language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install coveralls pycodestyle pep257 restructuredtext_lint
  - python setup.py install
script:
  - python setup.py test
  - pycodestyle --ignore=E501,W503 resync-simulator simulator tests
  - pep257 resync-simulator simulator tests
  - rst-lint README
  - coverage run --source=simulator setup.py test
after_success:
  - coveralls
