#!/usr/bin/python
"""
resync-client: The ResourceSync command line client

Created by Simeon Warner on 2012-04...
"""

import argparse

from resync.client import Client, ClientFatalError

def main():
    
    # Options and arguments
    p = argparse.ArgumentParser(description='ResourceSync sync script')
    p.add_argument('--sitemap', '-s', metavar='path=uri', type=str, action='store', nargs='*',
                   help="write out a sitemap using path=uri mappings")
    p.add_argument('--audit', '-a', action='store_true',
                   help="audit sync state of destination wrt source")
    p.add_argument('--delete', action='store_true',
                   help="allow files on destination to be deleted")
    p.add_argument('--checksum', '-c', action='store_true',
                   help="use checksum (md5) in addition to last modification time and size")
    p.add_argument('--verbose', '-v', action='store_true',
                   help="verbose")
    p.add_argument('src', type=str, action='store', nargs='?',
                   help='source')
    p.add_argument('dst', type=str, action='store', nargs='?',
                   help='destination')
    args = p.parse_args()

    c = Client( checksum=args.checksum,
                verbose=args.verbose )
    try:
        if (args.sitemap):
            # Create sitemap, args assumed to be base_path->base_uri mappings 
            print c.make_inventory(mappings=args.sitemap)
        else:
            # Either do sync or just audit
            if (args.src is None or args.dst is None):
                p.error("You must supply source and destination arguments")
            c.sync_or_audit(args.src, args.dst, 
                            allow_deletion=args.delete,
                            audit_only=args.audit)
    # Any problem we expect will come as a ClientFatalError, anything else 
    # is... an exception ;-)
    except ClientFatalError as e:
        p.error(e.message)

if __name__ == '__main__':
    main()
