#!/usr/bin/env python
# encoding: utf-8
"""
simulate-source: The ResourceSync command line tool for simulating a changing
Web data source.

Created by Bernhard Haslhofer on 2012-04-24.
Copyright 2012, ResourceSync.org. All rights reserved.
"""

import argparse
import yaml

from resync.source import Source
from resync.http import HTTPInterface

DEFAULT_CONFIG_FILE = 'config/default.yaml'

def main():
    
    # Define simulator options
    parser = argparse.ArgumentParser(
                            description = "ResourceSync Source Simulator")
    parser.add_argument('--config-file', '-c', 
                    default=DEFAULT_CONFIG_FILE,
                    help="the simulation configuration file")
    parser.add_argument('--port', '-p', type=int,
                    default=8888,
                    help="the HTTP interface port")
    parser.add_argument('--hostname', '-n',
                    default="localhost",
                    help="the hostname where the simulator is running")
    
    # Parse command line arguments
    args = parser.parse_args()

    # Load the YAML configuration file
    stream = file(args.config_file, 'r')
    config = yaml.load(stream)
    
    # Set up the source
    source_settings = config['source']
    source = Source(source_settings, args.hostname, args.port)
    
    # Set up and register the source inventory (if defined)
    if config.has_key('inventory'):
        klass_name = config['inventory']['class']
        mod = __import__('resync.source', fromlist=[klass_name])
        inventory_klass = getattr(mod, klass_name)
        inventory = inventory_klass(source, config['inventory'])
        source.add_inventory(inventory)
    
    # Set up and register change memory (if defined)
    if config.has_key('changememory'):
        klass_name = config['changememory']['class']
        mod = __import__('resync.changememory', fromlist=[klass_name])
        changemem_klass = getattr(mod, klass_name)
        changememory = changemem_klass(source, config['changememory'])
        source.add_changememory(changememory)
    
    # Set up and register publishers (if defined)
    if config.has_key('publisher'):
        klass_name = config['publisher']['class']
        mod = __import__('resync.publisher', fromlist=[klass_name])
        publisher_klass = getattr(mod, klass_name)
        publisher = publisher_klass(source, config['publisher'])
    
    # Attach event loggers;
    if config.has_key('logger'):
        klass_name = config['logger']['class']
        mod = __import__('resync.event_log', fromlist=[klass_name])
        logger_class = getattr(mod, klass_name)
        logger = logger_class(source, config['logger'])
    
    # Bootstrap the source
    source.bootstrap()
    
    # Start the Web interface, run the simulation
    # Attach HTTP interface to source
    http_interface = HTTPInterface(source)
    try:
        http_interface.start()
        source.simulate_changes()
    except KeyboardInterrupt:
        print "Exiting gracefully..."
    finally:
        http_interface.stop()

if __name__ == '__main__':
    main()