# Default ResourceSync simulator configuration

# Source parameter settings
source:
    name: Sample Simulator Settings
    number_of_resources: 2000
    change_frequency: 1
    event_types: [created, updated, deleted]
    average_payload: 1000
    max_events: -1

# Inventory implementation used in the simulation
inventory:
    class: DynamicSiteMap
    url: /sitemap.xml

# Change memory implementation used in the simulation
changememory:
    class: DynamicDigest
    url: /changes
    
# The publisher implementation to send notifications
publisher:
    class: SimplePublisher
    jid: publisher_jid
    pwd: pwd
    pubsub_node: node_name
    pubsub_jid: pubsub.host

# Event logger settings
logger:
    class: ConsoleEventLog
